"""Seed data for the DRHP Document Repository.

Each project auto-instantiates its own copy of these line items on first visit
so that deletes/uploads scoped to one project never affect another.
"""

DRHP_DOCUMENT_CHECKLIST = [
    {
        "category": "Constitutional & Foundational Documents",
        "order": 1,
        "items": [
            {"title": "Certificate of Incorporation (COI)", "remarks": "Including any conversion from private to public company"},
            {"title": "Memorandum of Association (MOA) — latest amended", "remarks": "All amendments upto date of filing; every object-clause change to be reflected"},
            {"title": "Articles of Association (AOA) — latest amended", "remarks": "Post-IPO AOA draft also required; confirm deletion of pre-emption / anti-dilution rights"},
            {"title": "Annual Returns (MGT-7) for last 3 years", "remarks": "Cross-verify with shareholding structure in DRHP"},
            {"title": "Certificate of Commencement of Business (INC-20A)", "remarks": "Applicable to companies incorporated after Nov 2019"},
            {"title": "PAN, TAN, CIN of the Company", "remarks": "Standard KYC identifiers for SEBI registration"},
        ],
    },
    {
        "category": "Board & Shareholder Resolutions",
        "order": 2,
        "items": [
            {"title": "Board Resolution for IPO Authorization", "remarks": "Approving fresh issue and/or OFS; filing of DRHP"},
            {"title": "Shareholder Special Resolution u/s 62(1)(c) — EGM/AGM", "remarks": "For fresh issue of shares; obtain certified true copy with vote count"},
            {"title": "Board Resolution for Increase in Authorized Share Capital", "remarks": "With SH-7 filed with ROC; verify effective date"},
            {"title": "Board Resolution — Appointment of Intermediaries", "remarks": "BRLMs, Legal Counsel, Registrar, Bankers, Monitoring Agency"},
            {"title": "Board Resolution — Formation of IPO Committee", "remarks": "Delegate authority on pricing, timing, allotment"},
            {"title": "Board Resolution — Adoption of Restated Financials", "remarks": "Approving restated accounts for IPO purposes"},
            {"title": "Board Resolution — Re-designation / Appointment of Directors", "remarks": "Board composition per SEBI listing norms (IDs, Woman Director)"},
            {"title": "Board Resolution — Final Approval of DRHP", "remarks": "Pre-filing approval with initialled DRHP annexed"},
            {"title": "Board Resolution — Adoption of Dividend Policy", "remarks": "Mandatory disclosure under SEBI LODR Reg. 43A"},
            {"title": "Board / Shareholder Resolution for Pre-IPO Placement (if any)", "remarks": "Specific resolution for any private placement before IPO"},
        ],
    },
    {
        "category": "Promoter & Key Personnel Disclosures",
        "order": 3,
        "items": [
            {"title": "Promoter KYC — PAN, Aadhaar, Passport copies", "remarks": "All individual and corporate promoters; cross-verify with RoC records"},
            {"title": "Promoter Group shareholding structure chart with lock-in periods", "remarks": "Visual org chart + table showing 36-month and 6-month lock-in separately"},
            {"title": "DIN declarations and DIR-8 forms from all Directors", "remarks": "Confirm no disqualification under Sec 164 Companies Act"},
            {"title": "Educational & professional credential certificates of KMPs", "remarks": "Schedule VI DRHP format requires qualification details"},
            {"title": "Promoter experience certificates / business history", "remarks": "Minimum 3 years track record as required under SEBI ICDR"},
            {"title": "Affidavits from Promoters & Directors — criminal / economic offenses", "remarks": "Standard SEBI-format affidavit; must be notarised"},
            {"title": "Non-Compete and Non-Solicitation Agreements (Promoters)", "remarks": "If promoter group has other business interests in same sector"},
            {"title": "Promoter Lock-in Undertakings — 36 months (MPC) & 6 months (balance)", "remarks": "Individual undertaking from each promoter entity"},
        ],
    },
    {
        "category": "Capital Structure & Share History",
        "order": 4,
        "items": [
            {"title": "Complete share capital history from incorporation", "remarks": "Every allotment event: date, no. of shares, price, consideration, allottee category"},
            {"title": "Form PAS-3 for all historical allotments", "remarks": "Including private placements, rights issues, ESOPs, bonus"},
            {"title": "Bonus / rights issue history with board & shareholder resolutions", "remarks": "Include record dates, ratio, entitlement basis"},
            {"title": "Pre-IPO placement details (if applicable)", "remarks": "Parties, price, number of shares, lock-in period (90 days)"},
            {"title": "ESOP scheme document, trust deed & grant letters", "remarks": "Per SEBI SBEB Regulations; all outstanding options must be disclosed"},
            {"title": "Shareholders' Agreements (SHA), SPAs, and Termination Agreements", "remarks": "Removal of superior rights (anti-dilution, tag-along, veto) before IPO"},
            {"title": "OFS Seller Intent Letters and offer size confirmation", "remarks": "Each selling shareholder to confirm OFS quantum in writing"},
            {"title": "Demat account statements of promoters (latest)", "remarks": "Confirms physical shares converted; confirms promoter holding"},
        ],
    },
    {
        "category": "Legal Documentation & Material Contracts",
        "order": 5,
        "items": [
            {"title": "Material Contracts (>5% or 10% of revenue threshold)", "remarks": "As defined by Board; attach or summarise in DRHP"},
            {"title": "Inter-se Agreements between Promoters / Selling Shareholders", "remarks": "Regarding OFS mechanics and price band"},
            {"title": "Escrow Agreements with Bankers", "remarks": "Application money management, refund, settlement"},
            {"title": "Syndicate / Underwriting Agreements with BRLMs", "remarks": "Confirm firm vs. soft underwriting commitment"},
            {"title": "Registrar Agreement (RTA Agreement)", "remarks": "Share allotment, refund processing, SEBI grievance norms"},
            {"title": "IP Assignment Deeds — trademarks, patents, domain names", "remarks": "All IP must be legally owned by the Company (not promoters)"},
            {"title": "Lease Deeds / Title Deeds for key properties", "remarks": "Registered lease for offices; ownership docs for plants"},
            {"title": "Technology / License Agreements", "remarks": "Any third-party software, franchise, or tech license material to business"},
            {"title": "Key Customer & Key Supplier Agreements", "remarks": "Material contracts per revenue/cost threshold; confirm change-of-control clauses"},
            {"title": "Loan / Facility Agreements with Lenders", "remarks": "All credit facilities; confirm prepayment penalties for IPO repayment objects"},
        ],
    },
    {
        "category": "Subsidiary, Associate & Group Company Documents",
        "order": 6,
        "items": [
            {"title": "COI, MOA/AOA of all Subsidiaries", "remarks": "Domestic and foreign subsidiaries; confirm step-down subsidiaries"},
            {"title": "Latest audited financials of all Subsidiaries / Associates", "remarks": "Required for consolidated statements; confirm audit status"},
            {"title": "Inter-company Agreements & Related Party Contracts", "remarks": "Loans, service agreements, guarantees between group entities"},
            {"title": "Board Resolutions of Subsidiaries for IPO-related actions", "remarks": "E.g., providing corporate guarantees, charge creation, waivers"},
            {"title": "List of Group Companies (as per SEBI ICDR definition)", "remarks": "Promoter-controlled companies even without shareholding by issuer"},
        ],
    },
    {
        "category": "Secretarial & Regulatory Filings",
        "order": 7,
        "items": [
            {"title": "Form SH-7 — Increase in Authorized Share Capital", "remarks": "Filed with ROC; obtain acknowledgement"},
            {"title": "Form MGT-14 — Special Resolutions", "remarks": "For IPO authorization, AOA/MOA amendments, ESOP, capital increase"},
            {"title": "Form DIR-12 — Director Appointment / Resignation / Redesignation", "remarks": "All changes to be current and reflected in ROC records"},
            {"title": "Certificate of Peer Review (Statutory Auditor)", "remarks": "CA firm must be SEBI-empaneled and peer-reviewed"},
            {"title": "No-Action / Exemption Letters from SEBI or other Regulators", "remarks": "For any specific relaxations sought"},
            {"title": "Secretarial Audit Reports (last 3 years)", "remarks": "Under Section 204 of Companies Act; by PCS"},
            {"title": "Annual Report including Board Report (last 3 years)", "remarks": "Contains statutory declarations, CSR report, BRSR if applicable"},
            {"title": "Register of Members (current extract)", "remarks": "Confirms promoter holdings, pre-IPO investors, ESOP pool"},
        ],
    },
    {
        "category": "Regulatory & Statutory Compliance Certificates",
        "order": 8,
        "items": [
            {"title": "Sector-specific Regulatory License / NOC", "remarks": "E.g., RBI (NBFC/Bank), IRDAI (Insurance), SEBI (Broking), FSSAI (Food)"},
            {"title": "Environmental / Pollution Clearances", "remarks": "Consent to Establish & Consent to Operate from SPCB (manufacturing companies)"},
            {"title": "GST Registration Certificate & Compliance Status", "remarks": "Confirm no material GST demand or dispute pending"},
            {"title": "PF & ESIC Compliance Certificates", "remarks": "Confirm contributions current; obtain from EPFO/ESIC portal"},
            {"title": "FEMA Compliance Certificates (if FDI/ODI/ECB involved)", "remarks": "Obtain from Company's FEMA counsel; confirm all filings with RBI"},
            {"title": "Import-Export Code (IEC) if applicable", "remarks": "From DGFT; relevant for companies with material import/export"},
            {"title": "Labour Law Compliance Certificates (Shops & Establishments, Factories)", "remarks": "State-level licences; CLRA for contract labour"},
            {"title": "Data Protection / IT Act Compliance (if applicable)", "remarks": "Especially relevant for technology / fintech companies under DPDPA 2023"},
        ],
    },
    {
        "category": "Financial Data, Auditor Certificates & Banker Documents",
        "order": 9,
        "items": [
            {"title": "Restated Summary Statements — 3 financial years", "remarks": "Balance Sheet, P&L, Cash Flow, Notes; per SEBI ICDR Sch. XVI"},
            {"title": "Audit Reports on Restated Financials (IPO-specific)", "remarks": "Separate from statutory audit; IPO-format report by peer-reviewed auditor"},
            {"title": "Interim Financials (if latest audit > 6 months old at filing)", "remarks": "Stub period financials reviewed (not audited) by statutory auditor"},
            {"title": "Management Discussion & Analysis (MD&A) Data — 3 years", "remarks": "Revenue, margins, KPIs, operational metrics with YoY comparisons"},
            {"title": "Related Party Transaction (RPT) List — 3 years", "remarks": "Per Ind AS 24 / AS-18; cross-verified with board approvals"},
            {"title": "Statement of Possible Special Tax Benefits", "remarks": "Auditor certificate; separate DRHP section required"},
            {"title": "Taxation Certificates from Auditors", "remarks": "Deferred tax position, transfer pricing, advance tax schedule"},
            {"title": "Solvency Certificate from Banker", "remarks": "Confirms company's banking relationship and account conduct"},
            {"title": "Banker's Certificate on Credit Facilities", "remarks": "Details of all outstanding fund-based and non-fund-based limits"},
            {"title": "Auditor Certificate on Minimum Promoter Contribution (MPC)", "remarks": "Confirms lock-in eligibility of shares per Reg. 14-16 SEBI ICDR"},
            {"title": "Working Capital Assessment Certificate (if applicable)", "remarks": "Required if working capital is one of the objects of the issue"},
            {"title": "CARO Report (last 3 years)", "remarks": "Companies Auditor's Report Order; any adverse findings must be disclosed"},
        ],
    },
    {
        "category": "Litigation, Defaults & Material Liabilities",
        "order": 10,
        "items": [
            {"title": "Litigation Summary — Tax, Civil, Criminal, Regulatory", "remarks": "Against Company, Subsidiaries, Promoters, Directors; with materiality threshold"},
            {"title": "Affidavits from Promoters & Directors (criminal / economic offenses)", "remarks": "Notarised; SEBI prescribed format"},
            {"title": "Search Reports on Properties & Charges", "remarks": "Independent legal counsel title report; confirm no undisclosed encumbrance"},
            {"title": "Details of MSME Dues & Aging Analysis", "remarks": "Outstanding payables; confirm MSME Form-1 filings with ROC"},
            {"title": "Show Cause Notices / Orders from Regulators (last 5 years)", "remarks": "SEBI, RBI, GST, IT, ED, ROC; even if closed / resolved"},
            {"title": "Statutory Demand Notices — Tax (Income Tax, GST, Customs)", "remarks": "Attach orders and status of appeals"},
            {"title": "NCLT / IBC Proceedings (if any)", "remarks": "Company or any group entity; confirm resolution status"},
        ],
    },
    {
        "category": "Objects of the Issue — Supporting Evidence",
        "order": 11,
        "items": [
            {"title": "At Least Two Independent Quotations for Equipment/Capex", "remarks": "From different vendors; not older than 6 months at DRHP filing"},
            {"title": "Debt Repayment Letters from Lenders", "remarks": "Outstanding amount, prepayment penalty; confirmed in writing"},
            {"title": "Monitoring Agency Agreement (fresh issue > INR 100 Cr)", "remarks": "Bank appointed as monitoring agency; per Reg. 41 SEBI ICDR"},
            {"title": "General Corporate Purposes (GCP) — Detailed Utilisation Plan", "remarks": "Max 25% of fresh issue; board-approved breakup required"},
            {"title": "Land Acquisition Documents / LOI for New Projects", "remarks": "If IPO proceeds fund land purchase or new facility"},
            {"title": "Project Feasibility Report / Appraisal by Bank / FI (if applicable)", "remarks": "For large greenfield projects; required by SEBI examiners"},
            {"title": "Approval from Technical Consultant for Capex Estimates", "remarks": "Validates cost estimates presented in Objects section"},
        ],
    },
    {
        "category": "Consent Letters, Certificates & Due Diligence Documents",
        "order": 12,
        "items": [
            {"title": "Consent Letter — Statutory Auditor (for DRHP inclusion)", "remarks": "Confirming consent to inclusion of audit reports in DRHP"},
            {"title": "Consent Letter — BRLMs", "remarks": "Accepting SEBI-prescribed BRLM responsibilities and due diligence"},
            {"title": "Consent Letter — Registrar to the Issue (RTA)", "remarks": "Accepting appointment and confirming compliance with SEBI regulations"},
            {"title": "Consent Letter — Legal Counsel (Domestic & International)", "remarks": "Accepting appointment as issuer counsel; confirms authorisation"},
            {"title": "Due Diligence Certificate (DDC) — BRLMs", "remarks": "Standard SEBI-prescribed DDC filed along with DRHP"},
            {"title": "Completed Due Diligence Questionnaire (DDQ)", "remarks": "Legal DDQ submitted by Company to BRLMs; forms basis of representations"},
            {"title": "Comfort Letter from Auditors (if required by BRLMs)", "remarks": "On financial statements; often required for institutional confidence"},
            {"title": "SEBI SCORES / NSE/BSE Empanelment Confirmations", "remarks": "Confirm BRLM and RTA empanelment is current"},
        ],
    },
    {
        "category": "Insurance Documents",
        "order": 13,
        "items": [
            {"title": "Directors & Officers (D&O) Insurance Policy", "remarks": "Mandatory for listed entities; confirm pre-IPO coverage"},
            {"title": "Property / Fire / Consequential Loss Insurance", "remarks": "For manufacturing plants, warehouses, key assets"},
            {"title": "Key-Man / Key Personnel Insurance (if any)", "remarks": "Confirm if any director/KMP life is insured for business continuity"},
            {"title": "Group Health / Workmen's Compensation Insurance", "remarks": "Employee welfare; confirm compliance with applicable Acts"},
            {"title": "Product / Professional Liability Insurance (if applicable)", "remarks": "For technology, pharma, financial services companies"},
        ],
    },
    {
        "category": "Industry Research & Market Data",
        "order": 14,
        "items": [
            {"title": "Industry Report — commissioned from CRISIL / CARE / ICRA or sector consultant", "remarks": "Must be recent (within 6 months of filing); grant of usage rights required"},
            {"title": "Competitive Benchmarking Data — listed peers on NSE/BSE", "remarks": "Revenue, margins, valuation multiples for peer set selection"},
            {"title": "Consent Letter from Research Agency for DRHP inclusion", "remarks": "Agency consent to quote their report; include disclaimer on methodology"},
            {"title": "Government / Ministry Data Sources (if cited in DRHP)", "remarks": "Confirm source citations are accurate and hyperlinked in DRHP"},
        ],
    },
    {
        "category": "Images and Pictures",
        "order": 15,
        "items": [
            {"title": "Promoter Pictures",                                 "remarks": "High-resolution head-shots of all promoters; required for the Promoters section of the DRHP"},
            {"title": "Promoter Family Pictures",                          "remarks": "Family photographs of promoters (where applicable); used in 'Our Promoters' section"},
            {"title": "KMP and Directors Pictures",                        "remarks": "Head-shots of all Key Managerial Personnel and Directors; used in 'Our Management' section"},
            {"title": "Office Pictures (Internal and External)",           "remarks": "Both interior and exterior shots of registered & corporate offices; used to illustrate 'Our Operations'"},
            {"title": "Manufacturing Facility Pictures",                   "remarks": "Wide and detail shots of plant, machinery, warehouses, R&D labs; used in 'Business Overview'"},
        ],
    },
]
